# Copyright (c) 2020 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

################################################################################
version: 2.1

commands:
  setup-build:
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.6"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Add bin directory to PATH
          command: |
            echo "export PATH=${CIRCLE_WORKING_DIRECTORY}/bin:$PATH" >> $BASH_ENV
      - run:
          name: Install fabric-tools
          command: |
            curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.0.0 -s
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

  run-build:
    steps:
      - run:
          name: Check formatting
          command: make format-check
      - run:
          name: Compile
          command: make compile
      - run:
          name: Unit tests
          command: make test
      - run:
          name: Package
          command: make package
      #- run: cat /dev/null | sbt test:compile

  run-integration-test:
    steps:
      - run:
          name: Integration test
          command: |
            ls
            make it
      - save_cache:
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
          key: v1-dependencies--{{ checksum "build.sbt" }}

  blackduck-scan:
    steps:
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
            ci-build ${CIRCLE_PROJECT_USERNAME}_${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} \
            --logging.level.com.synopsys.integration=DEBUG \
            --detect.tools=DETECTOR,BINARY_SCAN \
            --detect.notices.report=false \
            --detect.excluded.detector.types=GO_MOD \
            --detect.cleanup=false \
            --detect.cleanup.bdio.files=false \
            --detect.report.timeout=1100
# TODO cannot enable until upgraded to DAML 1.3.0
#            --detect.policy.check.fail.on.severities=MAJOR,CRITICAL,BLOCKER \
#            --detect.docker.image=digitalasset/daml-on-fabric:2.0.0 \
#            --detect.docker.image=digitalasset/daml-on-fabric-chaincode:2.0.0 \
      - store_artifacts:
          name: Store the Blackduck run artifacts
          path: /home/circleci/blackduck/runs

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.3.10
      JVM_OPTS: -Xmx3200m
      TERM: dumb      
    resource_class: xlarge
    steps:
      - setup-build
      - run-build
      - run-integration-test
            
  blackduck-build:
    working_directory: ~/builddir
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.3.10
    resource_class: xlarge
    steps:
      - setup-build
      - run-build
      - blackduck-scan

workflows:
  version: 2
  workflow:
    jobs:
      - build

  blackduck:
    triggers:
      - schedule:
          cron: "30 8 * * 1-5"
          filters:
             branches:
                only:
                  - master
    jobs:
      - blackduck-build:
          context: blackduck
